const PAYMENT_FLOWS = {
  REGISTER: "REGISTER",
  GUEST: "GUEST",
  SUBSCRIPTION: "SUBSCRIPTION",
};

const PAYMENT_REQUEST_TYPES = {
  HOSTED_CHECKOUT: "HOSTED_CHECKOUT",
  LINK_DE_PAGO: "LINK_DE_PAGO",
  SUBSCRIPTION: "SUBSCRIPTION",
};

const PAYMENT_TYPES = {
  ONE_CLICK: "ONE_CLICK",
  SPEI: "SPEI",
  CASH: "CASH",
  CARD: "CARD",
};

module.exports = { PAYMENT_FLOWS, PAYMENT_REQUEST_TYPES, PAYMENT_TYPES };
